name: Build Typst document
on: push

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            src/annotation-system.typ
            src/CFG-based-system.typ

      - name: Get build identifier
        id: identifier
        run: |
          DATE=$(date +%Y-%m-%d-%H:%M | tr ':' '_')
          BRANCH=$(git branch --show-current)
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "MOD=$BRANCH-$DATE" >> $GITHUB_ENV

      - name: Add identifier to PDF
        run: |
          for file in src/*.pdf; do
            mv "$file" "src/$(basename "$file" .pdf)-${{ env.MOD }}.pdf"
          done

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Kt-Uniqueness-System-${{ env.MOD }}
          path: "src/*.pdf"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: main.pdf
